title: "ampatchlab/nf-pdx"
subtitle: "Patient-derived xenograft Nextflow pipeline"
intro_text: False

report_header_info:
    - Contact E-mail: 'stephen.kazakoff@qimrberghofer.edu.au'
    - Application Type: 'Patient-derived xenograft Nextflow pipeline'

module_order:
    - fastqc:
        name: 'FastQC (raw)'
        anchor: 'fastqc-raw'
        target: 'FastQC'
        path_filters_exclude:
            - '*.trimmed_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (trimmed)'
        anchor: 'fastqc-trimmed'
        target: 'FastQC'
        path_filters:
            - '*.trimmed_fastqc.zip'
    - picard
    - samtools
    - mosdepth:
        name: 'Mosdepth (human)'
        anchor: 'mosdepth-human'
        target: 'Mosdepth'
        path_filters:
            - './human/*'
    - mosdepth:
        name: 'Mosdepth (mouse)'
        anchor: 'mosdepth-mouse'
        target: 'Mosdepth'
        path_filters:
            - './mouse/*'
    - qualimap:
        name: 'QualiMap (human)'
        anchor: 'qualimap-human'
        target: 'QualiMap'
        path_filters:
            - './human/*'
    - qualimap:
        name: 'QualiMap (mouse)'
        anchor: 'qualimap-mouse'
        target: 'QualiMap'
        path_filters:
            - './mouse/*'

extra_fn_clean_exts:
    - type: 'truncate'
      pattern: '.markdup'
      module:
        - mosdepth-human
        - mosdepth-mouse
        - qualimap-human
        - qualimap-mouse
        - Samtools

run_modules:
    - fastqc
    - cutadapt
    - picard
    - samtools
    - mosdepth
    - qualimap

exclude_modules:
    - custom_content
